### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by zooneon** [Cho-D-YoungRae/spring-example#1]
Testcontainers를 사용하면 좋은 점이 뭐야?

**Comment by Cho-D-YoungRae** [comment]
## 장점

- 각 테스트 마다 필요한 이미지를 통해 테스트 환경을 구성할 수 있음
  - 테스트를 할때마다 해당 환경을 직접 구성하지 않고 자동화
  - ex) 인메모리 DB를 이용해서 테스트를 하지않고 실제 DB를 이용한다거나... 기타 다른 테스트 환경들
- 컨테이너를 사용하기 때문에 테스트의 멱등성 확보
  - 테스트에 사용된 컨테이너는 테스트가 종료되면 이용되었던 컨테이너는 테스트가 종료되면서 삭제
  -  ex) 실제 DB에 데이터가 적용되지 않는다던가...

## 단점

- 테스트가 느려짐...
  - 컨테이너 생성 및 추가적인 어떤 동작이 있는 듯
  - 처음 실행시키는 테스트의 경우 image pull 의 시간도 

## 적용

- 실제 로컬에서 테스트할 때
- CI 등의 경우

**Comment by zooneon** [comment]
역시 자동화가 짱이네 👍
답변 고마워
